/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2024-02-26 11:57:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1702828562000L));
    _jspx_dependants.put("jar:file:/C:/petshop/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/semiproject/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/petshop/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/semiproject/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>상품 상세보기</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/productview.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../header.jsp", out, false);
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../navbar.jsp", out, false);
      out.write("\n");
      out.write("	<div id=\"container\">\n");
      out.write("		<div id=\"mid\">\n");
      out.write("			<div class=\"mid-top\">\n");
      out.write("				<div class=\"view_pic\">\n");
      out.write("					<img src=\"../fileupload/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productlist.pfilename}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"\" class=\"view_picture\">\n");
      out.write("				</div>\n");
      out.write("				<div class=\"view_order\">\n");
      out.write("					<div class=\"view_explan\">\n");
      out.write("						<div class=\"view_title\">\n");
      out.write("							");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productlist.pname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("							<p class=\"new_icon\">NEW</p>\n");
      out.write("						</div>\n");
      out.write("						<table>\n");
      out.write("							<tbody>\n");
      out.write("								<tr>\n");
      out.write("									<th>원산지</th>\n");
      out.write("									<td>한국</td>\n");
      out.write("								</tr>\n");
      out.write("								<tr class=\"product_price\">\n");
      out.write("									<th>판매가</th>\n");
      out.write("									<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productlist.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("원</td>\n");
      out.write("								</tr>\n");
      out.write("								<tr>\n");
      out.write("									<th>배송비</th>\n");
      out.write("									<td>3000원 (30,000만원 이상 구매시 무료)</td>\n");
      out.write("								</tr>\n");
      out.write("								<tr>\n");
      out.write("									<th>혜택</th>\n");
      out.write("									<td>선착순 100명 10% 할인</td>\n");
      out.write("								</tr>\n");
      out.write("								<tr>\n");
      out.write("									<th>평점</th>\n");
      out.write("									<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productlist.p_score}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("점</td>\n");
      out.write("								</tr>\n");
      out.write("							</tbody>\n");
      out.write("						</table>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"quantity\">\n");
      out.write("						<span class=\"select_count\">! 수량을 선택해주세요</span>\n");
      out.write("						<table>\n");
      out.write("							<tr>\n");
      out.write("								<td>이츠독 플로라 가든 프레임 하우스 옐로우</td>\n");
      out.write("								<td>수량\n");
      out.write("									<button>-</button>\n");
      out.write("									<span> 1 </span>\n");
      out.write("								<button>+</button>\n");
      out.write("								</td>\n");
      out.write("								<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productlist.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("원</td>\n");
      out.write("							</tr>\n");
      out.write("						</table>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"confirm_price\">\n");
      out.write("						<span class=\"price_text\">총 상품금액(수량)</span>\n");
      out.write("						<h3>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productlist.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("원</h3>\n");
      out.write("						<span class=\"count\">(1개)</span>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"select_buy\">\n");
      out.write("						<a href=\"/cart.do?pno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productlist.pno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&cnt=1\"><button type=\"button\">장바구니 담기</button></a>\n");
      out.write("						<a href=\"/orders.do?pno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productlist.pno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><button type=\"button\">바로구매</button></a>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"mid-mid\">\n");
      out.write("				");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productlist.pcontent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"mid-btm\">\n");
      out.write("				<div class=\"item_review\">\n");
      out.write("					<p>ITEM REVIEW</p>\n");
      out.write("					<table>\n");
      out.write("						<thead>\n");
      out.write("							<tr>\n");
      out.write("								<th>no</th>\n");
      out.write("								<th>subject</th>\n");
      out.write("								<th>name</th>\n");
      out.write("								<th>date</th>\n");
      out.write("								<th>stars</th>\n");
      out.write("							</tr>\n");
      out.write("						</thead>\n");
      out.write("						<tbody>\n");
      out.write("							<tr>\n");
      out.write("								<td>4</td>\n");
      out.write("								<td>너무 좋아요!</td>\n");
      out.write("								<td>댕댕사랑</td>\n");
      out.write("								<td>2023-11-11</td>\n");
      out.write("								<td>★★★★☆</td>\n");
      out.write("							</tr>\n");
      out.write("							<tr>\n");
      out.write("								<td>3</td>\n");
      out.write("								<td>너무 좋아요!</td>\n");
      out.write("								<td>댕댕사랑</td>\n");
      out.write("								<td>2023-11-09</td>\n");
      out.write("								<td>★★★★☆</td>\n");
      out.write("							</tr>\n");
      out.write("							<tr>\n");
      out.write("								<td>2</td>\n");
      out.write("								<td>너무 좋아요!</td>\n");
      out.write("								<td>댕댕사랑</td>\n");
      out.write("								<td>2023-09-21</td>\n");
      out.write("								<td>★★★★☆</td>\n");
      out.write("							</tr>\n");
      out.write("							<tr>\n");
      out.write("								<td>1</td>\n");
      out.write("								<td>너무 좋아요!</td>\n");
      out.write("								<td>댕댕사랑</td>\n");
      out.write("								<td>2023-08-02</td>\n");
      out.write("								<td>★★★★☆</td>\n");
      out.write("							</tr>\n");
      out.write("						</tbody>\n");
      out.write("					</table>\n");
      out.write("					<button>page_number</button>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<div class=\"item_QnA\">\n");
      out.write("					<p>ITEM QnA</p>\n");
      out.write("					<table>\n");
      out.write("						<thead>\n");
      out.write("							<tr>\n");
      out.write("								<th>no</th>\n");
      out.write("								<th>subject</th>\n");
      out.write("								<th>name</th>\n");
      out.write("								<th>date</th>\n");
      out.write("								<th>answer</th>\n");
      out.write("							</tr>\n");
      out.write("						</thead>\n");
      out.write("						<tbody>\n");
      out.write("							<tr>\n");
      out.write("								<td>Q4</td>\n");
      out.write("								<td>비밀글입니다</td>\n");
      out.write("								<td>댕댕사랑</td>\n");
      out.write("								<td>2023-11-11</td>\n");
      out.write("								<td>X</td>\n");
      out.write("							</tr>\n");
      out.write("							<tr>\n");
      out.write("								<td>Q3</td>\n");
      out.write("								<td>너무 좋아요!</td>\n");
      out.write("								<td>댕댕사랑</td>\n");
      out.write("								<td>2023-11-09</td>\n");
      out.write("								<td>X</td>\n");
      out.write("							</tr>\n");
      out.write("							<tr>\n");
      out.write("								<td>Q2</td>\n");
      out.write("								<td>비밀글입니다</td>\n");
      out.write("								<td>작성자</td>\n");
      out.write("								<td>2023-09-21</td>\n");
      out.write("								<td>O</td>\n");
      out.write("							</tr>\n");
      out.write("							<tr>\n");
      out.write("								<td>A2</td>\n");
      out.write("								<td>비밀글입니다</td>\n");
      out.write("								<td>관리자</td>\n");
      out.write("								<td>2023-09-22</td>\n");
      out.write("								<td></td>\n");
      out.write("							</tr>\n");
      out.write("							<tr>\n");
      out.write("								<td>Q1</td>\n");
      out.write("								<td>너무 좋아요!</td>\n");
      out.write("								<td>댕댕사랑</td>\n");
      out.write("								<td>2023-08-02</td>\n");
      out.write("								<td>O</td>\n");
      out.write("							</tr>\n");
      out.write("							<tr>\n");
      out.write("								<td>A1</td>\n");
      out.write("								<td>너무 좋아요!</td>\n");
      out.write("								<td>관리자</td>\n");
      out.write("								<td>2023-08-03</td>\n");
      out.write("								<td></td>\n");
      out.write("							</tr>\n");
      out.write("						</tbody>\n");
      out.write("					</table>\n");
      out.write("					<button>page_number</button>\n");
      out.write("					<div class=\"QnA_btn\">\n");
      out.write("						<button>문의하기</button>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
