/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2024-02-26 08:54:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1702828562000L));
    _jspx_dependants.put("jar:file:/C:/petshop/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/semiproject/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>회원 가입폼</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/join_pre.css\">\n");
      out.write("<script src=\"../resources/js/jquery-3.7.1.js\"></script>\n");
      out.write("<script src=\"../resources/js/validation.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div id=\"container\">\n");
      out.write("		<div id=\"top\">\n");
      out.write("			<div class=\"join_header_wrap\">\n");
      out.write("				<div class=\"join_header_inner\">\n");
      out.write("					<a href=\"/main.do\" title=\"홈으로\"><img class=\"logo\"\n");
      out.write("						src=\"../resources/img/logo/로고_01_logo2.2.jpg\"></a>\n");
      out.write("					<ol>\n");
      out.write("						<li class=\"page_on\"><span>01</span> 가입방법 <i\n");
      out.write("							class=\"fa-solid fa-caret-right\"></i></li>\n");
      out.write("						<li><span>02</span> 약관동의 <i class=\"fa-solid fa-caret-right\"></i></li>\n");
      out.write("						<li><span>03</span> 정보입력 <i class=\"fa-solid fa-caret-right\"></i></li>\n");
      out.write("						<li><span>04</span> 가입완료</li>\n");
      out.write("					</ol>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div id=\"mid\">\n");
      out.write("			<div class=\"join_main_visual_inner\">\n");
      out.write("				<div class=\"join_img\">\n");
      out.write("					<a href=\"\"><img class=\"backimg\" src=\"../resources/img/else/back_img01.jpg\"></a>\n");
      out.write("					<div class=\"join_text\">\n");
      out.write("						<span class=\"primary\">우리 반려동물도 뭘 먹을지 궁금해야 합니다,<br>\n");
      out.write("						<b>멍뭉꼬냥에 오신 것을 환영합니다</b></span><br> <span class=\"summary\">지금\n");
      out.write("							멍뭉꼬냥에 가입하시고 다양한 혜택을 만나보세요</span>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"member_login_shop\">\n");
      out.write("						<a href=\"/join1.do\" id=\"btnJoin\" class=\"shop_mall_join\"><span>멍뭉꼬냥\n");
      out.write("								회원가입 하기</span></a>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"member_guide_txt\">\n");
      out.write("						<p>\n");
      out.write("							이미 멍뭉꼬냥 회원이신가요? <a href=\"/login.do\" id=\"btnLoginMember\"><b>로그인</b></a>\n");
      out.write("						</p>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
