/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2024-02-26 08:52:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/footer.css\">\n");
      out.write("<div id=\"bottom\">\n");
      out.write("	<div class=\"btm-box\">\n");
      out.write("		<div class=\"cst-center\">\n");
      out.write("			<p class=\"info-title\">CUSTOMER CENTER</p>\n");
      out.write("			<br>\n");
      out.write("			<p class=\"info-content\">\n");
      out.write("				TEL 010-0000-0000 <br> Kakao team_2 <br> AM 10 ~ PM 6 <br>\n");
      out.write("				Closed ~ Weekend, Holiday\n");
      out.write("			</p>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"bank-info\">\n");
      out.write("			<p class=\"info-title\">BANK INFO</p>\n");
      out.write("			<br>\n");
      out.write("			<p class=\"info-content\">\n");
      out.write("				<span>농협 123-1234-1234-12</span> / <span>국민 123456-12-123456</span><br>\n");
      out.write("				예금주 : (주)team_2\n");
      out.write("			</p>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"btm-icon\">\n");
      out.write("			<ul class=\"btm-icon-list\">\n");
      out.write("				<li><a href=\"\"><img class=\"icon\" src=\"resources/img/icon/icon_quick1.png\" alt=\"\"></a></li>\n");
      out.write("				<li><a href=\"\"><img class=\"icon\" src=\"resources/img/icon/icon_quick2.png\" alt=\"\"></a></li>\n");
      out.write("				<li><a href=\"\"><img class=\"icon\" src=\"resources/img/icon/icon_quick3.png\" alt=\"\"></a></li>\n");
      out.write("				<li><a href=\"\"><img class=\"icon\" src=\"resources/img/icon/icon_quick4.png\" alt=\"\"></a></li>\n");
      out.write("				<li><a href=\"\"><img class=\"icon\" src=\"resources/img/icon/icon_quick5.png\" alt=\"\"></a></li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<footer id=\"ftr-box\">\n");
      out.write("		<div class=\"footer-info\">\n");
      out.write("			<div class=\"ftr-tags\">\n");
      out.write("				<a href=\"\">HOME</a> | <a href=\"\">COMPANY</a> | <a href=\"\">AGREEMENT</a>\n");
      out.write("				| <a href=\"\">PRIVACY POLICY</a> | <a href=\"\">GUIDE</a>\n");
      out.write("			</div>\n");
      out.write("			<p class=\"span-list\">\n");
      out.write("				<span>team_2 : KHacademy</span> <span>address : korea seoul</span> <span>tel\n");
      out.write("					: 1234-1234</span> <span>e-mail : team_2@naver.com</span> <br> <span>leader\n");
      out.write("					: choi jae won</span> <span>member : seok min / dong hyeon / ji\n");
      out.write("					seong / je heon / seung beom </span> <br> <span>copyright ⓒ\n");
      out.write("					team_2. All rights reserved. Design by team_2.</span>\n");
      out.write("			</p>\n");
      out.write("		</div>\n");
      out.write("	</footer>\n");
      out.write("</div>\n");
      out.write("<script src=\"../resources/js/script.js\"></script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
