/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2024-02-26 08:52:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1702828562000L));
    _jspx_dependants.put("jar:file:/C:/petshop/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/semiproject/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/petshop/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/semiproject/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>멍뭉꼬냥</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/main.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "navbar.jsp", out, false);
      out.write("\n");
      out.write("	<div id=\"mid\">\n");
      out.write("		<div class=\"mid-top\">\n");
      out.write("			<div class=\"main-prod-show\">\n");
      out.write("				<!-- 제일 큰 사진으로 주요 제품 등을 보여줌 -->\n");
      out.write("				<div class=\"main-prod\">\n");
      out.write("					<a href=\"\"><img id=\"main-prod-pic1\" class=\"main-prod-pic\"\n");
      out.write("						src=\"resources/img/main_product/main-pic1.jpg\" alt=\"\"></a>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"main-prod\">\n");
      out.write("					<a href=\"\"><img id=\"main-prod-pic2\" class=\"main-prod-pic\"\n");
      out.write("						src=\"resources/img/main_product/main-pic2.jpg\" alt=\"\"></a>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"main-prod\">\n");
      out.write("					<a href=\"\"><img id=\"main-prod-pic3\" class=\"main-prod-pic\"\n");
      out.write("						src=\"resources/img/main_product/main-pic3.jpg\" alt=\"\"></a>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"main-prod\">\n");
      out.write("					<a href=\"\"><img id=\"main-prod-pic4\" class=\"main-prod-pic\"\n");
      out.write("						src=\"resources/img/main_product/main-pic4.jpg\" alt=\"\"></a>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"main-prod\">\n");
      out.write("					<a href=\"\"><img id=\"main-prod-pic5\" class=\"main-prod-pic\"\n");
      out.write("						src=\"resources/img/main_product/main-pic5.jpg\" alt=\"\"></a>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"main-pic-button\">\n");
      out.write("				<!-- 버튼 클릭으로 메인 사진 선택 -->\n");
      out.write("				<button class=\"pic1\" onclick=\"selectPic(0)\"></button>\n");
      out.write("				<button class=\"pic2\" onclick=\"selectPic(1)\"></button>\n");
      out.write("				<button class=\"pic3\" onclick=\"selectPic(2)\"></button>\n");
      out.write("				<button class=\"pic4\" onclick=\"selectPic(3)\"></button>\n");
      out.write("				<button class=\"pic5\" onclick=\"selectPic(4)\"></button>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"mid-mid\"></div>\n");
      out.write("		<div class=\"board\">\n");
      out.write("			<div class=\"notice-board\">\n");
      out.write("				<h3 class=\"title-notice\">\n");
      out.write("					<a href=\"\">Notice / Event</a>\n");
      out.write("				</h3>\n");
      out.write("				<ul class=\"notice-list\">\n");
      out.write("					<li><a href=\"\">Notice 1</a></li>\n");
      out.write("					<li><a href=\"\">Notice 2</a></li>\n");
      out.write("					<li><a href=\"\">Event 2</a></li>\n");
      out.write("					<li><a href=\"\">Event 1</a></li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"review-board\">\n");
      out.write("				<h3 class=\"title-review\">\n");
      out.write("					<a href=\"\">Review Board</a>\n");
      out.write("				</h3>\n");
      out.write("				<ul class=\"review-list\">\n");
      out.write("					<li><a href=\"\">Review 4</a></li>\n");
      out.write("					<li><a href=\"\">Review 3</a></li>\n");
      out.write("					<li><a href=\"\">Review 2</a></li>\n");
      out.write("					<li><a href=\"\">Review 1</a></li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"QnA-board\">\n");
      out.write("				<h3 class=\"title-QnA\">\n");
      out.write("					<a href=\"\">Q/A Board</a>\n");
      out.write("				</h3>\n");
      out.write("				<ul class=\"QnA-list\">\n");
      out.write("					<li><a href=\"\">Q/A 4</a></li>\n");
      out.write("					<li><a href=\"\">Q/A 3</a></li>\n");
      out.write("					<li><a href=\"\">Q/A 2</a></li>\n");
      out.write("					<li><a href=\"\">Q/A 1</a></li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<div class=\"mid-bottom\">\n");
      out.write("		<div class=\"prod-board\">\n");
      out.write("			<h2>Home Sweet Home</h2>\n");
      out.write("			<div class=\"sub-prod-show\">\n");
      out.write("				<!-- 메인 제품 외의 주요 제품 목록 -->\n");
      out.write("				<a href=\"\"><img class=\"sub-prod-pic\"\n");
      out.write("					src=\"resources/img/products/house1.jpg\" alt=\"\"></a> <a href=\"\"><img\n");
      out.write("					class=\"sub-prod-pic\" src=\"resources/img/products/house2.jpg\" alt=\"\"></a> <a\n");
      out.write("					href=\"\"><img class=\"sub-prod-pic\"\n");
      out.write("					src=\"resources/img/products/house3.jpg\" alt=\"\"></a> <a href=\"\"><img\n");
      out.write("					class=\"sub-prod-pic\" src=\"resources/img/products/house4.jpg\" alt=\"\"></a>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<h2>WaGoo WaGoo</h2>\n");
      out.write("			<div class=\"sub-prod-show\">\n");
      out.write("				<!-- 메인 제품 외의 주요 제품 목록 -->\n");
      out.write("				<a href=\"\"><img class=\"sub-prod-pic\"\n");
      out.write("					src=\"resources/img/products/food1.jpg\" alt=\"\"></a> <a href=\"\"><img\n");
      out.write("					class=\"sub-prod-pic\" src=\"resources/img/products/food2.jpg\" alt=\"\"></a> <a\n");
      out.write("					href=\"\"><img class=\"sub-prod-pic\" src=\"resources/img/products/food3.jpg\"\n");
      out.write("					alt=\"\"></a> <a href=\"\"><img class=\"sub-prod-pic\"\n");
      out.write("					src=\"resources/img/products/food4.jpg\" alt=\"\"></a>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<h2>Let's Play</h2>\n");
      out.write("			<div class=\"sub-prod-show\">\n");
      out.write("				<!-- 메인 제품 외의 주요 제품 목록 -->\n");
      out.write("				<a href=\"\"><img class=\"sub-prod-pic\"\n");
      out.write("					src=\"resources/img/products/toy1.jpg\" alt=\"\"></a> <a href=\"\"><img\n");
      out.write("					class=\"sub-prod-pic\" src=\"resources/img/products/toy2.jpg\" alt=\"\"></a> <a\n");
      out.write("					href=\"\"><img class=\"sub-prod-pic\" src=\"resources/img/products/toy3.jpg\"\n");
      out.write("					alt=\"\"></a> <a href=\"\"><img class=\"sub-prod-pic\"\n");
      out.write("					src=\"resources/img/products/toy4.jpg\" alt=\"\"></a>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
