/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2024-02-26 10:51:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.orders;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class orders_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;
private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_1;
private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_2;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:substring", org.apache.taglibs.standard.functions.Functions.class, "substring", new Class[] {java.lang.String.class, int.class, int.class});
  _jspx_fnmap_1= org.apache.jasper.runtime.ProtectedFunctionMapper.getInstance();
  _jspx_fnmap_1.mapFunction("fn:substring", org.apache.taglibs.standard.functions.Functions.class, "substring", new Class[] {java.lang.String.class, int.class, int.class});
  _jspx_fnmap_1.mapFunction("fn:indexOf", org.apache.taglibs.standard.functions.Functions.class, "indexOf", new Class[] {java.lang.String.class, java.lang.String.class});
  _jspx_fnmap_2= org.apache.jasper.runtime.ProtectedFunctionMapper.getInstance();
  _jspx_fnmap_2.mapFunction("fn:substring", org.apache.taglibs.standard.functions.Functions.class, "substring", new Class[] {java.lang.String.class, int.class, int.class});
  _jspx_fnmap_2.mapFunction("fn:indexOf", org.apache.taglibs.standard.functions.Functions.class, "indexOf", new Class[] {java.lang.String.class, java.lang.String.class});
  _jspx_fnmap_2.mapFunction("fn:length", org.apache.taglibs.standard.functions.Functions.class, "length", new Class[] {java.lang.Object.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/petshop/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/semiproject/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1702828562000L));
    _jspx_dependants.put("jar:file:/C:/petshop/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/semiproject/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/petshop/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/semiproject/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>멍뭉꼬냥</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/orders.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../header.jsp", out, false);
      out.write("\n");
      out.write("	<div id=\"mid\">\n");
      out.write("		<h3>ORDER</h3>\n");
      out.write("		<div class=\"mid-top\">\n");
      out.write("			<div class=\"member_order_info\">\n");
      out.write("				<table>\n");
      out.write("					<tbody>\n");
      out.write("						<tr>\n");
      out.write("							<td rowspan=\"2\" class=\"rowspan2\">혜택 정보</td>\n");
      out.write("							<td class=\"first_td\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님,환영합니다</td>\n");
      out.write("						</tr>\n");
      out.write("						<tr class=\"second_tr\">\n");
      out.write("							<td class=\"second_td\"><a href=\"#\">사용 가능 쿠폰 : 1개</a></td>\n");
      out.write("						</tr>\n");
      out.write("					</tbody>\n");
      out.write("				</table>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"prod_order_confirm_table\">\n");
      out.write("				<div class=\"order_change_decrip\">! 상품의 옵션 및 수량 변경은 상품상세 또는\n");
      out.write("					장바구니에서 가능합니다.</div>\n");
      out.write("				<table>\n");
      out.write("					<tbody>\n");
      out.write("						<tr>\n");
      out.write("							<td colspan=\"9\">상품 주문내역</td>\n");
      out.write("						</tr>\n");
      out.write("						<tr class=\"table_td_head\">\n");
      out.write("							<td><input type=\"checkbox\"></td>\n");
      out.write("							<td>이미지</td>\n");
      out.write("							<td>상품정보</td>\n");
      out.write("							<td>판매가</td>\n");
      out.write("							<td>수량</td>\n");
      out.write("							<td>쿠폰여부</td>\n");
      out.write("							<td>배송구분</td>\n");
      out.write("							<td>배송비</td>\n");
      out.write("							<td>상품합계</td>\n");
      out.write("						</tr>\n");
      out.write("						");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("						<tr class=\"tr3\">\n");
      out.write("							<td colspan=\"9\"><span class=\"order_config_small_text\">상품구매금액\n");
      out.write("									<span class=\"result\"></span>원 + 배송비 3,000원 = 합계 :\n");
      out.write("							</span><span class=\"order_config_big_text\"><span\n");
      out.write("									class=\"final_result\"></span></span> <span\n");
      out.write("								class=\"order_config_small_text\">원</span></td>\n");
      out.write("						</tr>\n");
      out.write("					</tbody>\n");
      out.write("				</table>\n");
      out.write("				<div class=\"order_change_decrip\">! 상품의 옵션 및 수량 변경은 상품상세 또는\n");
      out.write("					장바구니에서 가능합니다.</div>\n");
      out.write("				<div class=\"select_order_cancel\">\n");
      out.write("					<span>선택한 상품 : </span>\n");
      out.write("					<button>X 삭제하기</button>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<div class=\"mid-mid\">\n");
      out.write("			<div class=\"order_order_info\">\n");
      out.write("				<div class=\"order_info_span\">\n");
      out.write("					<span class=\"span_title\">주문자 정보</span> <span><span\n");
      out.write("						class=\"required\">*</span> 필수입력사항</span>\n");
      out.write("				</div>\n");
      out.write("				<table>\n");
      out.write("					<tbody>\n");
      out.write("						<tr>\n");
      out.write("							<th>주문하시는 분 <span class=\"required\">*</span></th>\n");
      out.write("							<td><input type=\"text\" size=\"10\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\n");
      out.write("								readonly></td>\n");
      out.write("						</tr>\n");
      out.write("						<tr>\n");
      out.write("							<th>주소 <span class=\"required\">*</span></th>\n");
      out.write("							<td>\n");
      out.write("								<div class=\"order_address\">\n");
      out.write("									<input type=\"text\" class=\"copiedad1\" size=\"10\"\n");
      out.write("										value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.zip_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\n");
      out.write("									<button>우편번호 ></button>\n");
      out.write("									<br> <input type=\"text\" class=\"copiedad2\" size=\"30\"\n");
      out.write("										value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly> 기본주소 <br> <input\n");
      out.write("										type=\"text\" class=\"copiedad3\" size=\"30\"\n");
      out.write("										value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.detailaddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly> 나머지주소\n");
      out.write("								</div>\n");
      out.write("							</td>\n");
      out.write("						</tr>\n");
      out.write("						<tr>\n");
      out.write("							<th>일반 전화</th>\n");
      out.write("							<td><select name=\"telephone1\" id=\"telephone1\">\n");
      out.write("									<option value=\"02\">02</option>\n");
      out.write("									<option value=\"031\">031</option>\n");
      out.write("									<option value=\"032\">032</option>\n");
      out.write("							</select> - <input class=\"copiedt1\" type=\"text\" size=\"5\" maxlength=\"4\"\n");
      out.write("								readonly> - <input class=\"copiedt2\" type=\"text\" size=\"5\"\n");
      out.write("								maxlength=\"4\" readonly></td>\n");
      out.write("						</tr>\n");
      out.write("						<tr>\n");
      out.write("							<th>휴대전화 <span class=\"required\">*</span></th>\n");
      out.write("							<td><select name=\"mobilephone1\" id=\"mobilephone1\">\n");
      out.write("									<option value=\"02\">010</option>\n");
      out.write("									<option value=\"031\">011</option>\n");
      out.write("									<option value=\"032\">019</option>\n");
      out.write("							</select> - <input class=\"phoneNo1\" type=\"text\" size=\"5\" maxlength=4\n");
      out.write("								value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:substring(member.phone, 3, 7)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\"> - <input\n");
      out.write("								class=\"phoneNo2\" type=\"text\" size=\"5\" maxlength=4\n");
      out.write("								value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:substring(member.phone, 7, 11)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\"></td>\n");
      out.write("						</tr>\n");
      out.write("						<tr>\n");
      out.write("							<th>이메일 <span class=\"required\">*</span></th>\n");
      out.write("							<td><input type=\"text\"\n");
      out.write("								value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:substring(member.email, 0, fn:indexOf(member.email, '@'))}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_1));
      out.write("\"\n");
      out.write("								readonly>@ <input type=\"text\"\n");
      out.write("								value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:substring(member.email, fn:indexOf(member.email, '@') + 1, fn:length(member.email))}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_2));
      out.write("\"\n");
      out.write("								readonly> <select name=\"email\" id=\"email\">\n");
      out.write("									<option value=\"naver.com\">naver.com</option>\n");
      out.write("									<option value=\"gmail.com\">gmail.com</option>\n");
      out.write("									<option value=\"daum.net\">daum.net</option>\n");
      out.write("							</select>\n");
      out.write("								<p>- 이메일을 통해 주문처리과정을 보내드립니다</p>\n");
      out.write("								<p>- 이메일 주소란에는 반드시 수신가능한 이메일주소를 입력해주세요</p></td>\n");
      out.write("						</tr>\n");
      out.write("					</tbody>\n");
      out.write("				</table>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"deliver_order_info\">\n");
      out.write("				<div class=\"deliver_info_span\">\n");
      out.write("					<span class=\"span_title\">배송 정보</span> <span><span\n");
      out.write("						class=\"required\">*</span> 필수입력사항</span>\n");
      out.write("				</div>\n");
      out.write("				<table>\n");
      out.write("					<tbody>\n");
      out.write("						<tr>\n");
      out.write("							<th>배송지 선택</th>\n");
      out.write("							<td><input type=\"radio\" id=\"order\" name=\"address\"\n");
      out.write("								value=\"same\" onchange=\"copyAddress()\"><label for=\"order\">주문자와\n");
      out.write("									동일</label> <input type=\"radio\" id=\"deliver\" name=\"address\" value=\"new\"\n");
      out.write("								onchange=\"clearAddress()\"><label for=\"deliver\">새로운\n");
      out.write("									배송지</label></td>\n");
      out.write("						</tr>\n");
      out.write("						<tr>\n");
      out.write("							<th>주소 <span class=\"required\">*</span></th>\n");
      out.write("							<td>\n");
      out.write("								<div class=\"deliver_address\">\n");
      out.write("									<input class=\"copyAddress1\" type=\"text\" size=\"10\">\n");
      out.write("									<button>우편번호 ></button>\n");
      out.write("									<br> <input class=\"copyAddress2\" type=\"text\" size=\"30\">\n");
      out.write("									기본주소 <br> <input class=\"copyAddress3\" type=\"text\"\n");
      out.write("										size=\"30\"> 나머지주소\n");
      out.write("								</div>\n");
      out.write("							</td>\n");
      out.write("						</tr>\n");
      out.write("						<tr>\n");
      out.write("							<th>일반 전화</th>\n");
      out.write("							<td><select name=\"telephone2\" id=\"telephone2\">\n");
      out.write("									<option value=\"02\">02</option>\n");
      out.write("									<option value=\"031\">031</option>\n");
      out.write("									<option value=\"032\">032</option>\n");
      out.write("							</select> - <input class=\"copytel1\" type=\"text\" size=\"5\" maxlength=4>\n");
      out.write("								- <input class=\"copytel2\" type=\"text\" size=\"5\" maxlength=4>\n");
      out.write("							</td>\n");
      out.write("						</tr>\n");
      out.write("						<tr>\n");
      out.write("							<th>휴대전화 <span class=\"required\">*</span></th>\n");
      out.write("							<td><select name=\"mobilephone2\" id=\"mobilephone2\">\n");
      out.write("									<option value=\"010\">010</option>\n");
      out.write("									<option value=\"011\">011</option>\n");
      out.write("									<option value=\"016\">016</option>\n");
      out.write("									<option value=\"019\">019</option>\n");
      out.write("							</select> - <input class=\"copyphone1\" type=\"text\" size=\"5\" maxlength=4>\n");
      out.write("								- <input class=\"copyphone2\" type=\"text\" size=\"5\" maxlength=4>\n");
      out.write("							</td>\n");
      out.write("						</tr>\n");
      out.write("						<tr>\n");
      out.write("							<th>배송메시지</th>\n");
      out.write("							<td><textarea name=\"delive_message\" id=\"delive_message\"\n");
      out.write("									cols=\"70\" rows=\"5\"></textarea></td>\n");
      out.write("						</tr>\n");
      out.write("					</tbody>\n");
      out.write("				</table>\n");
      out.write("				<div class=\"deliver_agree\">\n");
      out.write("					<p>배송정보 제공방침</p>\n");
      out.write("					<p>본 상품의 원활한 배송을 위하여 회원님의 주소를 상품판매업체 및 배송업체에 제공합니다.</p>\n");
      out.write("					<input type=\"checkbox\">동의\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<div class=\"mid-btm\">\n");
      out.write("			<div class=\"expected_order\">\n");
      out.write("				<div class=\"expected_order_price\">\n");
      out.write("					<span>결제예정 금액</span>\n");
      out.write("				</div>\n");
      out.write("				<table>\n");
      out.write("					<thead>\n");
      out.write("						<tr>\n");
      out.write("							<th>총 주문 금액<span>(배송비포함)</span></th>\n");
      out.write("							<th>총 할인 금액</th>\n");
      out.write("							<th>총 결제예정 금액</th>\n");
      out.write("						</tr>\n");
      out.write("					</thead>\n");
      out.write("					<tbody>\n");
      out.write("						<tr>\n");
      out.write("							<td><span><span class=\"final_result\"></span></span> 원</td>\n");
      out.write("							<td>- <span>0 </span> 원\n");
      out.write("							</td>\n");
      out.write("							<td>= <span><span class=\"final_result\"></span></span> 원\n");
      out.write("							</td>\n");
      out.write("						</tr>\n");
      out.write("					</tbody>\n");
      out.write("				</table>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"order_method\">\n");
      out.write("				<div class=\"method_title\">\n");
      out.write("					<span>결제수단</span>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"order_method_container\">\n");
      out.write("					<div class=\"method_detail\">\n");
      out.write("						<div class=\"select_method\">\n");
      out.write("							<input type=\"radio\" id=\"bankbook\" name=\"method_payment\"\n");
      out.write("								value=\"bankbook\" checked><label for=\"bankbook\"> 무통장 입금</label> <input\n");
      out.write("								type=\"radio\" id=\"card\" name=\"method_payment\" value=\"card\"><label\n");
      out.write("								for=\"card\"> 카드결제</label> <input type=\"radio\" id=\"kakao\"\n");
      out.write("								name=\"method_payment\" value=\"kakao\"><label for=\"kakao\">\n");
      out.write("								카카오 페이</label> <input type=\"radio\" id=\"payco\" name=\"method_payment\"\n");
      out.write("								value=\"payco\"><label for=\"payco\"> 페이코</label> <input\n");
      out.write("								type=\"radio\" id=\"pay_phone\" name=\"method_payment\"\n");
      out.write("								value=\"pay_phone\"><label for=\"pay_phone\"> 휴대폰 결제</label>\n");
      out.write("							<input type=\"radio\" id=\"sspay\" name=\"method_payment\"\n");
      out.write("								value=\"sspay\"><label for=\"sspay\"> 삼성페이</label>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"select_method_datail\">\n");
      out.write("							<table class=\"detail_table\">\n");
      out.write("								<tbody>\n");
      out.write("									<tr>\n");
      out.write("										<td class=\"detail_table_title\">입금자명</td>\n");
      out.write("										<td><input type=\"text\"></td>\n");
      out.write("									</tr>\n");
      out.write("									<tr>\n");
      out.write("										<td class=\"detail_table_title\">입금은행</td>\n");
      out.write("										<td><select name=\"bank_select\" id=\"bank_select\">\n");
      out.write("												<option value=\"농협\">농협은행 123-1234-1234-12</option>\n");
      out.write("												<option value=\"국민\">국민은행 123456-12-123456</option>\n");
      out.write("										</select></td>\n");
      out.write("									</tr>\n");
      out.write("								</tbody>\n");
      out.write("							</table>\n");
      out.write("							<div class=\"cash_bill\">\n");
      out.write("								<div class=\"bill_yes_no\">\n");
      out.write("									<p>현금 영수증 신청</p>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"bill_yes\">\n");
      out.write("									<input type=\"radio\" id=\"yes\" name=\"bill\" value=\"yes\" checked><label\n");
      out.write("										for=\"yes\">현금영수증 신청</label> <input type=\"radio\" id=\"no\"\n");
      out.write("										name=\"bill\" value=\"no\"><label for=\"no\">신청 안함</label>\n");
      out.write("									<table>\n");
      out.write("										<tbody>\n");
      out.write("											<tr>\n");
      out.write("												<td class=\"bill_yes_td\">구분</td>\n");
      out.write("												<td><input type=\"radio\" id=\"personal\" name=\"who\"\n");
      out.write("													value=\"personal\"><label for=\"personal\">개인</label> <input\n");
      out.write("													type=\"radio\" id=\"company\" name=\"who\" value=\"company\" checked><label\n");
      out.write("													for=\"company\">사업자</label></td>\n");
      out.write("											</tr>\n");
      out.write("											<!-- <tr class=\"select_personal\">\n");
      out.write("                                            <td>핸드폰 번호</td>\n");
      out.write("                                            <td><select name=\"phone\" id=\"phone\">\n");
      out.write("                                                <option value=\"010\">010</option>\n");
      out.write("                                                <option value=\"011\">011</option>\n");
      out.write("                                                <option value=\"016\">016</option>\n");
      out.write("                                                <option value=\"019\">019</option>\n");
      out.write("                                            </select>-<input type=\"text\">-<input type=\"text\"></td>\n");
      out.write("                                        </tr> -->\n");
      out.write("											<tr class=\"select_company\">\n");
      out.write("												<td class=\"bill_yes_td\">사업자 번호</td>\n");
      out.write("												<td><input type=\"text\" size=\"15\"></td>\n");
      out.write("											</tr>\n");
      out.write("										</tbody>\n");
      out.write("									</table>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"withdrawal_policy\">\n");
      out.write("								<div class=\"withdrawal_policy_title\">청약철회방침</div>\n");
      out.write("								<div class=\"withdrawal_policy_box\">\n");
      out.write("									<div class=\"policy_textarea\">\n");
      out.write("										<p>①“주식회사 스노우볼 인터내셔널”과 재화등의 구매에 관한 계약을 체결한 이용자는 수신확인의 통지를\n");
      out.write("											받은 날부터 7일 이내에는 청약의 철회를 할 수 있습니다.</p>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"final_config\">\n");
      out.write("						<div class=\"final_config_price\">\n");
      out.write("							<p>최종결제 금액</p>\n");
      out.write("							<p>\n");
      out.write("								<span><span class=\"final_result\"></span></span>원\n");
      out.write("							</p>\n");
      out.write("						</div>\n");
      out.write("						<p>\n");
      out.write("							<input type=\"checkbox\"> 결제정보를 확인하였으며, <br> 구매진행에\n");
      out.write("							동의합니다.\n");
      out.write("						</p>\n");
      out.write("						");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"info_desk_box\">\n");
      out.write("					<div class=\"interest_free\">\n");
      out.write("						<table>\n");
      out.write("							<tbody>\n");
      out.write("								<tr>\n");
      out.write("									<th>무이자 할부 이용안내</th>\n");
      out.write("								</tr>\n");
      out.write("								<tr>\n");
      out.write("									<td>- 무이자할부가 적용되지 않은 상품과 무이자할부가 가능한 상품을 동시에 구매할 경우 전체 주문\n");
      out.write("										상품 금액에 대해 무이자할부가 적용되지 않습니다</td>\n");
      out.write("								</tr>\n");
      out.write("								<tr>\n");
      out.write("									<td>- 무이자할부를 원하시는 경우 장바구니에서 무이자할부 상품만 선택하여 주문하여 주시기 바랍니다.</td>\n");
      out.write("								</tr>\n");
      out.write("							</tbody>\n");
      out.write("						</table>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"using_info\">\n");
      out.write("						<table>\n");
      out.write("							<tbody>\n");
      out.write("								<tr>\n");
      out.write("									<th>이용안내</th>\n");
      out.write("								</tr>\n");
      out.write("								<tr>\n");
      out.write("									<td>\n");
      out.write("										<div>WindowXP 서비스팩2를 설치하신후 결제가 정상적인 단계로 처리되지 않는경우, 아래의\n");
      out.write("											절차에 따라 해결하시기 바랍니다.</div>\n");
      out.write("										<div>아래의 쇼핑몰일 경우에는 모든 브라우저 사용이 가능합니다.</div>\n");
      out.write("										<div>세금계산서 발행 안내</div>\n");
      out.write("										<div>부가가치세법 변경에 따른 신용카드매출전표 및 세금계산서 변경안내</div>\n");
      out.write("										<div>현금영수증 이용안내</div>\n");
      out.write("									</td>\n");
      out.write("								</tr>\n");
      out.write("							</tbody>\n");
      out.write("						</table>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../footer.jsp", out, false);
      out.write("\n");
      out.write("	<script src=\"../resources/js/orders.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("							");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("							");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /orders/orders.jsp(51,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty product }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("								<tr class=\"tr2\">\n");
          out.write("									<td class=\"td1\"><input type=\"checkbox\"></td>\n");
          out.write("									<td class=\"td2\"><a href=\"#\"><img\n");
          out.write("											src=\"../fileupload/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.pfilename}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" alt=\"\"></a></td>\n");
          out.write("									<td class=\"td3\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.pname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\n");
          out.write("										<p class=\"new_icon\">NEW</p>\n");
          out.write("									</td>\n");
          out.write("									");
          out.write("\n");
          out.write("									<td class=\"td4\"><span class=\"p_price\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("원</span></td>\n");
          out.write("									<td class=\"td5\"><span class=\"p_count\">1</span></td>\n");
          out.write("									<td class=\"td6\">No</td>\n");
          out.write("									<td class=\"td7\">기본배송</td>\n");
          out.write("									<td class=\"td8\">3,000원</td>\n");
          out.write("									<td class=\"td9\"><span class=\"result\"></span></td>\n");
          out.write("								</tr>\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("								");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
      // /orders/orders.jsp(70,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/orders/orders.jsp(70,8) '${cartlist }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${cartlist }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /orders/orders.jsp(70,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("cart");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("									<tr>\n");
            out.write("										<td class=\"td1\"><input type=\"checkbox\"></td>\n");
            out.write("										<td class=\"td2\"><img\n");
            out.write("											src=\"../fileupload/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.pfilename}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"\"></td>\n");
            out.write("										<td class=\"td3\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.pname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\n");
            out.write("											<p class=\"new_icon\">NEW</p>\n");
            out.write("										</td>\n");
            out.write("										<td class=\"td4\"><span class=\"p_price\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span></td>\n");
            out.write("										<td class=\"td5\"><span class=\"p_count\">1</span></td>\n");
            out.write("										<!-- orders 테이블에 수량  -->\n");
            out.write("										<td class=\"td6\">No</td>\n");
            out.write("										<td class=\"td7\">기본배송</td>\n");
            out.write("										<td class=\"td8\">3,000원</td>\n");
            out.write("										<td class=\"td9\"><span class=\"result\"></span></td>\n");
            out.write("									</tr>\n");
            out.write("								");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent(null);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("							");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("							");
          if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /orders/orders.jsp(352,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty product }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("								<a href=\"/purchaseconfirm.do?pno=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.pno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"><button type=\"button\">결제하기</button></a>\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("								<a href=\"/purchaseconfirm.do\"><button type=\"button\">결제하기</button></a>\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }
}
